### ISSUE TITLE
Cannot load pretrained weights

### ISSUE THREAD

**Issue by Reasat** [AdalbertoCq/Learning-a-low-dimensional-manifold-of-realcancer-tissue#1]
Hello 

I was trying to load the [pretrained weights](https://figshare.com/articles/PathologyGAN_Encoder_tar_gz/12006492) to the model graph provided [here](https://github.com/AdalbertoCq/Learning-a-low-dimensional-manifold-of-realcancer-tissue/blob/master/models/generative/gans/PathologyGAN_Encoder.py)

I run into some missing key error.

> 2020-08-27 11:19:32.301792: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key discriminator/attention_block_5/conv_layer_1/bias not found in checkpoi
nt
Traceback (most recent call last):
  File "D:\Miniconda3\envs\pathology-gan\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "D:\Miniconda3\envs\pathology-gan\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Miniconda3\envs\pathology-gan\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key discriminator/attention_block_5/conv_layer_1/bias not found in checkpoint
         [[{{node save/RestoreV2}}]]

Note: I am using all the libraries at the version specified in the requirement files except tensorflow. I am using 1.14.0 instead of 1.12.0 as I was running into [this](https://github.com/tensorflow/models/issues/8932) issue.

**Comment by AdalbertoCq** [comment]
Hey Tahsin,

I’ll take a look, there seems to be a mismatch with the pretained weights and the instantiation of the discriminator. It should be easy to fix, I’m kind of busy for the rest of the week but I’ll get it done for early next. 

Do you mind if I ask what are you interested in doing with the model? Let me know if I can help with any question you may have, I’ll be happy to chat about it.

Thanks,
Adal

**Comment by Reasat** [comment]
Hello Adal

Thanks for looking into it!

I am working on some Lung cancer images obtained here at Vanderbilt. We are trying to annotate the histological patterns in the images. To speed up annotations for pathologists I am trying to integrate deep learning solutions in an annotation framework [napari](https://github.com/napari/napari).

I am trying to figure out if features extracted from pre-trained networks are sufficient to annotate these images with minimum supervision from the pathologists. I want to use the GAN as a feature extractor. Based on the features I would run a linear classifier that will allow the pathologists to train/retrain the classifier on the fly and preferably speed up annotation. My experiments suggest that features extracted from networks trained on ImageNet have the capability of classifying some of these classes.

Let me know if you have further questions! And if you want to chat more about the idea or see a demo of the software, I would be happy to discuss it further!

Thanks 

Tahsin

**Comment by AdalbertoCq** [comment]
Hey Tahsin,

Yeah, sounds like a feasible idea. 

Sounds good, I think it will be good to chat. I can also give you some insight of what features our model has been able to identify and isolate in the latent space.

I'll shoot you an email. Thanks!
Adal
